version: '3.3'

networks:
  graylog:
    external: true

services:
  graylog:
    image: graylog/graylog:4.3.7
    user: $USER
    volumes:
      - ./journal:/usr/share/graylog/data/journal
      - ./graylog.conf:/usr/share/graylog/data/config/graylog.conf
      - ./plugin:/usr/share/graylog/plugin
    environment:
      - GRAYLOG_PASSWORD_SECRET=AdjasdajiAapapsidsaj22ewsdaj9
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=292128924e5d65baeaa7c155b83a775922459d9c57f13558a5aac1fe799baa4c
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:7555
      - GRAYLOG_HTTP_EXTERNAL_URI=http://graylog.com.br/
      - GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL=http://192.168.10.152:7555
      - MONGODB_URI=mongodb://mongodb
        #  - GRAYLOG_TRANSPORT_EMAIL_HOSTNAME=smtp.gmail.com
        #  - GRAYLOG_TRANSPORT_EMAIL_ENABLED=true
        #  - GRAYLOG_TRANSPORT_EMAIL_PORT=465
        # - GRAYLOG_TRANSPORT_EMAIL_USE_AUTH=true
        #  - GRAYLOG_TRANSPORT_EMAIL_USE_TLS=true
        #  - GRAYLOG_TRANSPORT_EMAIL_USE_SSL=true
        #  - GRAYLOG_TRANSPORT_FROM_EMAIL=
        # - GRAYLOG_TRANSPORT_SUBJECT_PREFIX=[graylog]
    ports:
      # Graylog web interface and REST API
      - 7555:7555
      # Syslog TCP
      - 8514:8514
      # Syslog UDP
      - 8514:8514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      - graylog
    restart: always
